language: android

env:
  global:
    - secure: "SBlXs4v/M3GD1tRaT6zmMXVpMCUaL/oNcSjGWdHgI56DO5NOmTBmDW5kJTT5y0u0U7aE1/Dq22iXPut8NLxWsEi/20xBq3bXQh9ngRkvOstNX7Y0LqnhKBtPixnMIx07xAjUPYCmunJakCT7Hr4fqZAGfUwA4a3ZzRa/KVeNx2A="
    - secure: "OVfIL3ggaGcDgJJhdWxYTCo3u38SNPNUNPsv6adHp5wW0Y2n1CF1zcAnZXhTkGEjoGvi0RuV8ZLG9jbmQdqxd17qBeBf2XPWKxyG1SUfegDVSy9OPF8BY11Fsp9I5RP1W3T/c32KTc7zvhtAivq9mbcrBYJZhDCKpZkdTNliFQ0="

android:
  components:
  - platform-tools
  - tools
  - android-23
  - build-tools-23.0.2
  - extra-google-m2repository
  - extra-android-m2repository

before_install:
  - echo $GPG_PASS | gpg --passphrase-fd 0 local.properties.gpg
  - echo $GPG_PASS | gpg --passphrase-fd 0 settings/service_account.json.gpg
  - echo $GPG_PASS | gpg --passphrase-fd 0 settings/release.keystore.gpg

before_script:
  - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"

after_success:
  - .buildscript/deploy_alpha.sh

script: "./gradlew check"

branches:
  except:
    - gh-pages

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9870bec6049c7309e68
    on_success: change
    on_failure: always
